export const VIDEO_GENERATION_POLLING_INTERVAL = 5000;
export const VIDEO_GENERATION_TASK_TIMEOUT = 60 * 60 * 1000;
export const VIDEO_GENERATION_MAX_RETRIES = Math.ceil(
  VIDEO_GENERATION_TASK_TIMEOUT / VIDEO_GENERATION_POLLING_INTERVAL,
);
