export const PHONE_VERIFICATION_CODE_TTL_SECONDS = 300;
export const PHONE_VERIFICATION_MAX_ATTEMPTS = 3;
export const PHONE_VERIFICATION_RESEND_COOLDOWN_SECONDS = 60;
export const PHONE_VERIFICATION_REDIS_PREFIX = 'phone-verification';
export const PHONE_VERIFICATION_CODE_LENGTH = 6;
